### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lotus33** [DominiLux/amdgpu-pro-fans#7]
Thanks!

**Comment by PROteinBY** [comment]
Really, thanks) Kubuntu 16.10 Radeon RX 480 GPUPRO 16.50 work fine)

**Comment by DominiLux** [comment]
My pleasure.  At the time no one knew how to accomplish this so I set out to solve the issue.  The main reason was to provide an easy to use template for future developers to follow to understand how to manipulate GPU attributes in Linux.  I've seen a lot of advanced features incorporated into various other software since I released this which after looking at the code was a spin off of the concepts I outlined in this project.  I'm glad I made a difference.  I am no longer actively developing on this project anymore because it's purpose of providing a template for other developers has been achieved.  I am working on a much larger scale project tho to manage enterprise grade computational clusters but I have yet to begin inviting team members to work on the project with me.  It will be an enterprise grade solution for remote management and monitoring of ALL GPU's within a large scale data center deployment.  Open sourced and apache license so that it will be business friendly.
